// // จัดการ promise errors ให้ไปที่ error handler กลาง
// export const asyncHandler = (fn) => (req, res, next) =>
//   Promise.resolve(fn(req, res, next)).catch(next);
